// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TwojeHity.Database;

#nullable disable

namespace TwojeHity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230628173820_favorite")]
    partial class favorite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TwojeHity.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ID_songId")
                        .HasColumnType("int");

                    b.Property<int?>("ID_userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ID_songId");

                    b.HasIndex("ID_userId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("TwojeHity.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("album")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rank")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("TwojeHity.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TwojeHity.Models.Favorite", b =>
                {
                    b.HasOne("TwojeHity.Models.Song", "ID_song")
                        .WithMany("Favorites")
                        .HasForeignKey("ID_songId");

                    b.HasOne("TwojeHity.Models.User", "ID_user")
                        .WithMany("Favorites")
                        .HasForeignKey("ID_userId");

                    b.Navigation("ID_song");

                    b.Navigation("ID_user");
                });

            modelBuilder.Entity("TwojeHity.Models.Song", b =>
                {
                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("TwojeHity.Models.User", b =>
                {
                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
